# GitHub Sponsors (Free to enable once applied)
github: [a2w-A, algo2world]

# Custom sponsorship links
custom:
  - https://algo2world.com#sponsor
  - https://a2w.in/support

# Community Platforms
patreon: algo2world
ko_fi: algo2world
buy_me_a_coffee: algo2world
